/* Statblock 5e v3.0.0 - Foundry VTT v14 / D&D5e v6 */
const MODULE_ID="statblock-5e";
const SUPPORTED_ITEMS=new Set(["race","class","subclass"]);
Hooks.once("init",()=>console.log(`${MODULE_ID} | Initializing v3.0.0`));
Hooks.once("ready",()=>console.log(`${MODULE_ID} | Ready`));

Hooks.on("renderActorDirectory",(_app,html)=>{
 const root=html instanceof HTMLElement?html:html?.[0]; if(!root)return;
 const header=root.querySelector(".directory-header .action-buttons")||root.querySelector(".directory-header");
 if(!header||header.querySelector(`[data-${MODULE_ID}]`))return;
 const b=document.createElement("button"); b.type="button"; b.dataset.statblock5e="true"; b.innerHTML='<i class="fa-solid fa-file-import"></i> Import 5e Content';
 b.title="Import a D&D 5e monster, NPC, species, class, subclass, weapon, or attack"; b.addEventListener("click",openImporter); header.appendChild(b);
});

function openImporter(){
 const D=foundry?.applications?.api?.DialogV2; if(!D)return ui.notifications.error("Statblock 5e requires Foundry VTT v14.");
 const content=`<div class="statblock-5e-importer"><p><strong>Import D&D 5e content from copied text or a text-based PDF.</strong></p><p class="hint">Use the website's normal Copy command. This module does not log in, scrape, bypass access controls, or download protected website content.</p><div class="form-group"><label>Content type</label><select name="contentType"><option value="auto">Auto-detect</option><option value="monster">Monster / NPC</option><option value="race">Species / Race</option><option value="class">Class</option><option value="subclass">Subclass</option><option value="weapon">Weapon / Attack</option></select></div><div class="form-group"><button type="button" id="sb5e-paste"><i class="fa-solid fa-paste"></i> Paste Clipboard Text</button></div><div class="form-group"><label>PDF or text file</label><input id="sb5e-file" type="file" accept=".pdf,.txt,.md,.text,.json,application/pdf,text/plain,application/json"></div><div class="form-group"><label>Source text</label><textarea id="sb5e-text" name="sourceText" rows="24" placeholder="Paste the complete statblock, weapon entry, species, class, or subclass here..."></textarea></div></div>`;
 new D({window:{title:"Statblock 5e Importer",icon:"fa-solid fa-file-import"},position:{width:860},content,buttons:[
  {action:"import",label:"Import",icon:"fa-solid fa-file-import",default:true,callback:async(_e,button)=>{const form=button.form,text=String(form.elements.sourceText?.value||"").trim();if(!text){ui.notifications.warn("Paste text or load a readable file first.");return false;}await importContent(text,form.elements.contentType?.value||"auto");return true;}},
  {action:"cancel",label:"Cancel",icon:"fa-solid fa-xmark"}
 ],render:(_e,dialog)=>{const root=dialog.element;root.querySelector("#sb5e-paste")?.addEventListener("click",async()=>{try{root.querySelector("#sb5e-text").value=await navigator.clipboard.readText();ui.notifications.info("Clipboard text pasted.");}catch(err){console.warn(`${MODULE_ID} | Clipboard permission denied`,err);ui.notifications.warn("Clipboard access was blocked. Click the text box and press Ctrl+V / Cmd+V.");}});root.querySelector("#sb5e-file")?.addEventListener("change",async event=>{const file=event.target.files?.[0];if(!file)return;try{root.querySelector("#sb5e-text").value=await readSourceFile(file);ui.notifications.info(`Loaded ${file.name}. Review the text before importing.`);}catch(err){console.error(err);ui.notifications.error(err.message||"Could not read the file.");}});}}).render({force:true});
}
async function readSourceFile(file){return file.name.toLowerCase().endsWith(".pdf")?extractPdfText(file):file.text();}
async function extractPdfText(file){
 const bytes=new Uint8Array(await file.arrayBuffer()),raw=new TextDecoder("latin1").decode(bytes),chunks=[];let cursor=0;
 while(cursor<raw.length){const stream=raw.indexOf("stream",cursor);if(stream<0)break;let start=stream+6;if(raw[start]==="\r")start++;if(raw[start]==="\n")start++;const end=raw.indexOf("endstream",start);if(end<0)break;const header=raw.slice(Math.max(0,raw.lastIndexOf("obj",stream-1)),stream);let data=bytes.slice(start,end);try{if(/\/FlateDecode/.test(header)&&typeof DecompressionStream!=="undefined")data=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(new DecompressionStream("deflate"))).arrayBuffer());}catch(err){console.warn(`${MODULE_ID} | PDF stream decompression failed`,err);}const st=new TextDecoder("latin1").decode(data),out=extractPdfOperators(st);if(out)chunks.push(out);cursor=end+9;}
 const result=chunks.join("\n").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();if(!result)throw new Error("No selectable text was found. Scanned/image-only PDFs need OCR first.");return result;
}
function extractPdfOperators(stream){const output=[],regex=/\((?:\\.|[^\\)])*\)\s*Tj|\[(?:(?:\\.|[^\]])*?)\]\s*TJ/g;for(const match of stream.matchAll(regex)){const parts=match[0].match(/\((?:\\.|[^\\)])*\)/g)||[];const text=parts.map(decodePdfString).join("");if(text)output.push(text);}return output.join("\n");}
function decodePdfString(v){return v.slice(1,-1).replace(/\\([\\()])/g,"$1").replace(/\\n/g,"\n").replace(/\\r/g,"\n").replace(/\\t/g,"\t").replace(/\\([0-7]{1,3})/g,(_m,o)=>String.fromCharCode(parseInt(o,8)));}

async function importContent(source,requestedType){const text=normalize(source),type=requestedType==="auto"?detectType(text):requestedType;try{if(type==="monster")await importMonster(text);else if(SUPPORTED_ITEMS.has(type))await importGameItem(text,type);else if(type==="weapon")await importWeaponEntry(text);else throw new Error(`Unsupported content type: ${type}`);}catch(err){console.error(`${MODULE_ID} | Import failed`,err);ui.notifications.error(`Import failed: ${err.message||err}`);}}
function detectType(text){const t=flatten(text);if(/(?:armor\s*class|\bAC\b)\s*[:\-]?\s*\d+/i.test(t)&&/(?:hit\s*points|\bHP\b)\s*[:\-]?\s*\d+/i.test(t)&&/\b(?:STR|DEX|CON|INT|WIS|CHA|Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma)\b\s*[:\-]?\s*\d+/i.test(t))return"monster";if(/melee weapon attack|ranged weapon attack|weapon properties|weapon mastery|damage\s*:\s*\d+d\d+/i.test(t))return"weapon";if(/subclass features|subclass|archetype|college|domain|circle|oath|patron|tradition/i.test(t))return"subclass";if(/hit die|class features|starting equipment|multiclassing/i.test(t))return"class";if(/ability score increase|species traits|racial traits|creature type/i.test(t))return"race";return"monster";}

async function importMonster(text){const p=parseMonster(text),actor=await Actor.create({name:p.name,type:"npc",system:{}}),u={};if(p.ac!=null)u["system.attributes.ac.flat"]=p.ac;if(p.hp!=null){u["system.attributes.hp.value"]=p.hp;u["system.attributes.hp.max"]=p.hp;}if(p.hpFormula)u["system.attributes.hp.formula"]=p.hpFormula;if(p.speed!=null)u["system.attributes.movement.walk"]=p.speed;if(p.cr)u["system.details.cr"]=p.cr;if(p.alignment)u["system.details.alignment"]=p.alignment;if(p.size)u["system.traits.size"]=p.size;if(p.creatureType)u["system.details.type.value"]=p.creatureType;if(p.proficiency!=null)u["system.attributes.prof"]=p.proficiency;if(p.passive!=null)u["system.attributes.senses.passive"]=p.passive;for(const[a,v]of Object.entries(p.abilities))u[`system.abilities.${a}.value`]=v;if(p.languages.length)u["system.traits.languages.value"]=p.languages;u["system.details.biography.value"]=sourceHtml(text);await actor.update(u);let attacks=0;for(const entry of p.entries){if(entry.attack){if(await createAttackItem(actor,entry))attacks++;}else await createActionItem(actor,entry);}actor.sheet.render(true);ui.notifications.info(`Imported ${actor.name}: ${attacks} attack item(s), ${p.entries.length-attacks} action item(s).`);}
function parseMonster(text){const lines=text.split("\n").map(cleanLine).filter(Boolean),flat=flatten(text),abilities={},patterns={str:/\b(?:STR|Strength)\s*[:\-]?\s*(\d+)/i,dex:/\b(?:DEX|Dexterity)\s*[:\-]?\s*(\d+)/i,con:/\b(?:CON|Constitution)\s*[:\-]?\s*(\d+)/i,int:/\b(?:INT|Intelligence)\s*[:\-]?\s*(\d+)/i,wis:/\b(?:WIS|Wisdom)\s*[:\-]?\s*(\d+)/i,cha:/\b(?:CHA|Charisma)\s*[:\-]?\s*(\d+)/i};for(const[k,r]of Object.entries(patterns)){const m=flat.match(r);if(m)abilities[k]=Number(m[1]);}const hp=flat.match(/(?:hit\s*points|\bHP\b)\s*[:\-]?\s*(\d+)(?:\s*\(([^)]+)\))?/i),ac=flat.match(/(?:armor\s*class|\bAC\b)\s*[:\-]?\s*(\d+)/i),speed=flat.match(/(?:speed|movement)\s*[:\-]?\s*([\d,]+)\s*ft\.?/i),cr=flat.match(/(?:challenge|CR)\s*[:\-]?\s*(\d+(?:\/\d+)?(?:\.\d+)?)/i),prof=flat.match(/(?:proficiency\s*bonus|PB)\s*[:\-]?\s*\+?(\d+)/i),passive=flat.match(/passive\s*(?:perception|wisdom)\s*[:\-]?\s*(\d+)/i),size=flat.match(/\b(Tiny|Small|Medium|Large|Huge|Gargantuan)\b/i),alignment=flat.match(/\b(lawful\s+good|neutral\s+good|chaotic\s+good|lawful\s+neutral|true\s+neutral|chaotic\s+neutral|lawful\s+evil|neutral\s+evil|chaotic\s+evil|unaligned)\b/i);return{name:findMonsterName(lines),abilities,ac:ac?Number(ac[1]):null,hp:hp?Number(hp[1]):null,hpFormula:hp?.[2]||"",speed:speed?Number(speed[1].replace(/,/g,"")):null,cr:cr?.[1]||"",proficiency:prof?Number(prof[1]):null,passive:passive?Number(passive[1]):null,size:normalizeSize(size?.[1]),creatureType:parseCreatureType(flat),alignment:alignment?.[1]||"",languages:parseLanguages(flat),entries:parseActionSections(lines)};}
function findMonsterName(lines){for(const line of lines.slice(0,10)){if(/^(armor class|hit points|speed|str|dex|con|int|wis|cha|challenge|proficiency bonus|languages|senses)\b/i.test(line))continue;if(/^(tiny|small|medium|large|huge|gargantuan)\b.*\b(aberration|beast|celestial|construct|dragon|elemental|fey|fiend|giant|humanoid|monstrosity|ooze|plant|undead)\b/i.test(line))continue;return line;}return"Imported Monster";}
function parseActionSections(lines){const starts=/^(actions?|bonus actions?|reactions?|legendary actions?)$/i,entries=[];let inSection=false,current=null;for(const line of lines){if(starts.test(line)){if(current)entries.push(current);current=null;inSection=true;continue;}if(inSection&&/^(lair actions?|spellcasting|description|equipment|regional effects?)$/i.test(line)){if(current)entries.push(current);break;}if(!inSection)continue;const m=line.match(/^([^.!?]{2,100})\.\s+(.+)/);if(m&&/(attack|spell|damage|save|hit|recharge|heal|condition)/i.test(m[2])){if(current)entries.push(current);current=makeEntry(m[1],m[2]);}else if(current)current.description+=` ${line}`;}if(current)entries.push(current);return entries.slice(0,60);}
function makeEntry(name,description){const attack=/\b(?:melee|ranged)\s+(?:weapon|spell)?\s*attack\b|\battack roll\b|\bto hit\b/i.test(description);return{name:name.trim(),description:description.trim(),attack,...parseAttack(description)};}
function parseAttack(text){const bonus=text.match(/([+-]\d+)\s*to\s*hit/i)?.[1]??null,damage=text.match(/(\d+)\s*d\s*(\d+)(?:\s*([+-])\s*(\d+))?\s*([a-z]+)?\s*damage/i),reach=text.match(/reach\s+(\d+)\s*ft/i)?.[1],range=text.match(/range\s+(\d+)\s*(?:\/\s*(\d+)\s*)?ft/i),ability=text.match(/\b(Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma)\b/i)?.[1]?.slice(0,3).toLowerCase()||null;return{bonus:bonus==null?null:Number(bonus),number:damage?Number(damage[1]):1,die:damage?`d${damage[2]}`:"d6",modifier:damage?.[4]?Number(`${damage[3]||"+"}${damage[4]}`):0,damageType:damage?.[5]?.toLowerCase()||null,range:range?Number(range[1]):(/\branged\b/i.test(text)?60:5),longRange:range?.[2]?Number(range[2]):null,ability,ranged:/\branged\s+(?:weapon\s+)?attack/i.test(text)};}

async function createAttackItem(actor,entry){try{const data={name:entry.name,type:"weapon",img:"icons/weapons/swords/sword-short.webp",system:{description:{value:`<p>${escapeHtml(entry.description)}</p>`},type:{value:"natural",subtype:""},actionType:entry.ranged?"rwak":"mwak",ability:entry.ability||(entry.ranged?"dex":"str"),attack:{bonus:entry.bonus==null?"":String(entry.bonus),flat:true},damage:{base:{number:entry.number||1,denomination:entry.die||"d6",bonus:entry.modifier||0,types:entry.damageType?[entry.damageType]:[]}},range:{value:entry.range??(entry.ranged?60:5),long:entry.longRange??null,units:"ft"},equipped:true,proficient:true}};const item=await Item.create(data,{parent:actor});await addAttackActivity(item,entry);return true;}catch(err){console.warn(`${MODULE_ID} | Attack import failed`,entry.name,err);await createActionItem(actor,entry);return false;}}
async function addAttackActivity(item,entry){const activity={type:"attack",name:"Attack",activation:{type:"action"},attack:{ability:entry.ability||(entry.ranged?"dex":"str"),bonus:entry.bonus==null?"":String(entry.bonus),flat:true,type:{value:entry.ranged?"ranged":"melee",classification:"weapon"}},damage:{includeBase:true,parts:[{number:entry.number||1,denomination:entry.die||"d6",bonus:entry.modifier||0,types:entry.damageType?[entry.damageType]:[]}]},range:{value:entry.range??(entry.ranged?60:5),long:entry.longRange??null,units:"ft"}};try{if(item.system?.activities?.create){await item.system.activities.create(activity);return;}}catch(err){console.debug(`${MODULE_ID} | Activity creation fallback`,err);}try{const id=foundry.utils.randomID();await item.update({[`system.activities.${id}`]:{_id:id,...activity}});}catch(err){console.debug(`${MODULE_ID} | Activity could not be attached; weapon item retained`,err);}}
async function createActionItem(actor,entry){try{await Item.create({name:entry.name,type:"feat",system:{description:{value:`<p>${escapeHtml(entry.description)}</p>`}}},{parent:actor});}catch(err){console.warn(`${MODULE_ID} | Action item failed`,entry.name,err);}}

async function importWeaponEntry(text){const parsed=makeEntry(findEntryName(text),text.replace(/^.*?\.\s+/,""));if(!parsed.attack&&!/damage|weapon|attack/i.test(text))throw new Error("No weapon or attack information was detected.");const actor=await Actor.create({name:"Imported Weapon",type:"npc",system:{}});await createAttackItem(actor,parsed);actor.sheet.render(true);ui.notifications.info(`Imported weapon/attack: ${parsed.name}`);}
function findEntryName(text){return(text.split("\n").map(cleanLine).find(Boolean)||"Imported Weapon").replace(/\.$/,"").slice(0,100);}
async function importGameItem(text,type){const lines=text.split("\n").map(cleanLine).filter(Boolean),system={description:{value:sourceHtml(text)}};if(type==="class"){system.levels=Number(flatten(text).match(/levels?\s*[:\-]?\s*(\d+)/i)?.[1]||1);system.hitDie=flatten(text).match(/hit\s*die\s*[:\-]?\s*(d\d+)/i)?.[1]||"d8";}const item=await Item.create({name:lines[0]||`Imported ${type}`,type,system});item.sheet.render(true);ui.notifications.info(`Imported ${type}: ${item.name}`);}
function parseCreatureType(text){return text.match(/\b(?:Tiny|Small|Medium|Large|Huge|Gargantuan)\b\s+([A-Za-z]+)/i)?.[1]?.toLowerCase()||"";}
function parseLanguages(text){const m=text.match(/languages?\s*[:\-]?\s*([^.;]+?)(?=\s+(?:challenge|actions?|reactions?|legendary|spellcasting|senses)\b|$)/i);return(m?.[1]||"").split(/[,;]/).map(s=>s.trim()).filter(Boolean);}
function normalizeSize(v){return({tiny:"tiny",small:"sm",medium:"med",large:"lg",huge:"huge",gargantuan:"grg"})[String(v||"").toLowerCase()]||null;}
function sourceHtml(text){return`<p><strong>Imported by Statblock 5e v3.0.0</strong></p><pre>${escapeHtml(text)}</pre>`;}
function normalize(text){return String(text).replace(/\r\n?/g,"\n").replace(/[\u00a0\u200b]/g," ").replace(/[ \t]+/g," ").replace(/\n[ \t]+/g,"\n");}
function flatten(text){return String(text).replace(/\n+/g," ").replace(/\s{2,}/g," ");}
function cleanLine(line){return String(line).replace(/[\u00a0\u200b]/g," ").replace(/[ \t]+/g," ").trim();}
function escapeHtml(text){return String(text).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
