/* Statblock 5e v3.1.0 - Foundry VTT v14 / D&D5e v6 */
const MODULE_ID="statblock-5e";
const ITEM_TYPES=new Set(["race","class","subclass"]);
Hooks.once("init",()=>console.log(`${MODULE_ID} | Initializing v3.1.0`));
Hooks.once("ready",()=>console.log(`${MODULE_ID} | Ready`));
Hooks.on("renderActorDirectory",(_app,html)=>{const root=html instanceof HTMLElement?html:html?.[0];if(!root)return;const header=root.querySelector(".directory-header .action-buttons")||root.querySelector(".directory-header");if(!header||header.querySelector("[data-statblock5e]"))return;const b=document.createElement("button");b.type="button";b.dataset.statblock5e="true";b.innerHTML='<i class="fa-solid fa-file-import"></i> Import 5e Content';b.addEventListener("click",openImporter);header.appendChild(b);});
function openImporter(){const D=foundry?.applications?.api?.DialogV2;if(!D)return ui.notifications.error("Statblock 5e requires Foundry VTT v14.");const content=`<div class="statblock-5e-importer"><p><strong>Import D&D 5e content</strong></p><p class="hint">Copy text normally from a supported website. This module does not scrape, log in, bypass controls, or download protected website content.</p><div class="form-group"><label>Content to create</label><select name="contentType"><option value="auto">Auto-detect</option><option value="monster">Monster / NPC</option><option value="weapon">Weapon</option><option value="attack">Attack</option><option value="race">Species / Race</option><option value="class">Class</option><option value="subclass">Subclass</option><option value="lair">Lair Action</option></select></div><div class="form-group"><button type="button" id="sb5e-paste"><i class="fa-solid fa-paste"></i> Paste Clipboard Text</button></div><div class="form-group"><label>PDF or text file</label><input id="sb5e-file" type="file" accept=".pdf,.txt,.md,.text,.json,application/pdf,text/plain,application/json"></div><div class="form-group"><label>Source text</label><textarea id="sb5e-text" name="sourceText" rows="24" placeholder="Paste the complete entry here..."></textarea></div></div>`;new D({window:{title:"Statblock 5e Importer",icon:"fa-solid fa-file-import"},position:{width:860},content,buttons:[{action:"import",label:"Import",icon:"fa-solid fa-file-import",default:true,callback:async(_e,button)=>{const form=button.form;const text=String(form.elements.sourceText?.value||"").trim();if(!text){ui.notifications.warn("Paste text or load a readable file first.");return false;}await importContent(text,form.elements.contentType?.value||"auto");return true;}},{action:"cancel",label:"Cancel",icon:"fa-solid fa-xmark"}],render:(_e,dialog)=>{const root=dialog.element;root.querySelector("#sb5e-paste")?.addEventListener("click",async()=>{try{root.querySelector("#sb5e-text").value=await navigator.clipboard.readText();ui.notifications.info("Clipboard text pasted.");}catch(err){console.warn(err);ui.notifications.warn("Clipboard access was blocked. Click the text box and press Ctrl+V / Cmd+V.");}});root.querySelector("#sb5e-file")?.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{root.querySelector("#sb5e-text").value=await readFile(f);ui.notifications.info(`Loaded ${f.name}.`);}catch(err){ui.notifications.error(err.message||"Could not read the file.");}});}}).render({force:true});}
async function readFile(file){return file.name.toLowerCase().endsWith(".pdf")?extractPdf(file):file.text();}
async function extractPdf(file){const bytes=new Uint8Array(await file.arrayBuffer()),raw=new TextDecoder("latin1").decode(bytes),out=[];let c=0;while(c<raw.length){const s=raw.indexOf("stream",c);if(s<0)break;let a=s+6;if(raw[a]==="\r")a++;if(raw[a]==="\n")a++;const e=raw.indexOf("endstream",a);if(e<0)break;const h=raw.slice(Math.max(0,raw.lastIndexOf("obj",s-1)),s);let d=bytes.slice(a,e);try{if(/\/FlateDecode/.test(h)&&typeof DecompressionStream!=="undefined")d=new Uint8Array(await new Response(new Blob([d]).stream().pipeThrough(new DecompressionStream("deflate"))).arrayBuffer());}catch(_){}const t=new TextDecoder("latin1").decode(d);const x=extractPdfOperators(t);if(x)out.push(x);c=e+9;}const result=out.join("\n").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();if(!result)throw new Error("No selectable text was found. Scanned PDFs need OCR first.");return result;}
function extractPdfOperators(s){const out=[];for(const m of s.matchAll(/\((?:\\.|[^\\)])*\)\s*Tj|\[(?:(?:\\.|[^\]])*?)\]\s*TJ/g)){const p=m[0].match(/\((?:\\.|[^\\)])*\)/g)||[];const t=p.map(decodePdf).join("");if(t)out.push(t);}return out.join("\n");}
function decodePdf(v){return v.slice(1,-1).replace(/\\([\\()])/g,"$1").replace(/\\n/g,"\n").replace(/\\r/g,"\n").replace(/\\t/g,"\t").replace(/\\([0-7]{1,3})/g,(_,o)=>String.fromCharCode(parseInt(o,8)));}
async function importContent(source,type){const text=normalize(source);const t=type==="auto"?detectType(text):type;try{if(t==="monster")return importMonster(text);if(ITEM_TYPES.has(t))return importSimpleItem(text,t);if(t==="weapon")return importStandaloneWeapon(text);if(t==="attack")return importStandaloneAttack(text);if(t==="lair")return importLairAction(text);throw new Error(`Unsupported content type: ${t}`);}catch(e){console.error(`${MODULE_ID} | Import failed`,e);ui.notifications.error(`Import failed: ${e.message||e}`);}}
function detectType(text){const t=flatten(text);if(/(?:armor class|\bAC\b)\s*[:\-]?\s*\d+/i.test(t)&&/(?:hit points|\bHP\b)\s*[:\-]?\s*\d+/i.test(t)&&/\b(?:STR|DEX|CON|INT|WIS|CHA)\b\s*[:\-]?\s*\d+/i.test(t))return"monster";if(/lair action|lair actions/i.test(t))return"lair";if(/melee weapon attack|ranged weapon attack|\+\d+\s+to\s+hit/i.test(t))return"attack";if(/weapon properties|weapon mastery|damage\s*:\s*\d+d\d+/i.test(t))return"weapon";if(/subclass features|subclass|archetype|college|domain|circle|oath|patron|tradition/i.test(t))return"subclass";if(/hit die|class features|starting equipment|multiclassing/i.test(t))return"class";if(/ability score increase|species traits|racial traits|creature type/i.test(t))return"race";return"monster";}
function parseMonster(text){const lines=text.split("\n").map(clean).filter(Boolean),flat=flatten(text),abilities={};for(const[k,n]of Object.entries({str:"STR",dex:"DEX",con:"CON",int:"INT",wis:"WIS",cha:"CHA"})){const m=flat.match(new RegExp(`\\b${n}\\b\\s*[:\\-]?\\s*(\\d+)`,`i`));if(m)abilities[k]=Number(m[1]);}const hp=flat.match(/(?:hit points|\bHP\b)\s*[:\-]?\s*(\d+)(?:\s*\(([^)]+)\))?/i),ac=flat.match(/(?:armor class|\bAC\b)\s*[:\-]?\s*(\d+)/i),speed=flat.match(/(?:speed|movement)\s*[:\-]?\s*([\d,]+)\s*ft/i),cr=flat.match(/(?:challenge|CR)\s*[:\-]?\s*(\d+(?:\/\d+)?(?:\.\d+)?)/i),prof=flat.match(/(?:proficiency bonus|PB)\s*[:\-]?\s*\+?(\d+)/i),passive=flat.match(/passive\s+(?:perception|wisdom)\s*[:\-]?\s*(\d+)/i),align=flat.match(/\b(lawful\s+good|neutral\s+good|chaotic\s+good|lawful\s+neutral|true\s+neutral|chaotic\s+neutral|lawful\s+evil|neutral\s+evil|chaotic\s+evil|unaligned)\b/i),size=flat.match(/\b(Tiny|Small|Medium|Large|Huge|Gargantuan)\b/i);return{name:findName(lines),abilities,ac:ac&&+ac[1],hp:hp&&+hp[1],formula:hp?.[2]||"",speed:speed&&+speed[1].replace(/,/g,""),cr:cr?.[1]||"",prof:prof&&+prof[1],passive:passive&&+passive[1],alignment:align?.[1]||"",size:size?.[1]||"",entries:parseSections(lines)};}
function findName(lines){for(const l of lines.slice(0,10)){if(/^(armor class|hit points|speed|str|dex|con|int|wis|cha|challenge|proficiency bonus|languages|senses)\b/i.test(l))continue;if(/^(tiny|small|medium|large|huge|gargantuan)\b.*\b(aberration|beast|celestial|construct|dragon|elemental|fey|fiend|giant|humanoid|monstrosity|ooze|plant|undead)\b/i.test(l))continue;return l;}return"Imported Monster";}
function parseSections(lines){const entries=[],heads=/^(actions?|bonus actions?|reactions?|legendary actions?|lair actions?)$/i,stop=/^(spellcasting|description|equipment|regional effects?)$/i;let section="",cur=null;for(const l of lines){if(heads.test(l)){if(cur)entries.push(cur);cur=null;section=l.toLowerCase();continue;}if(section&&stop.test(l)){if(cur)entries.push(cur);cur=null;section="";continue;}if(!section)continue;const m=l.match(/^([^.!?]{2,100})\.\s+(.+)/);if(m){if(cur)entries.push(cur);cur=entry(m[1],m[2],section);}else if(cur)cur.description+=` ${l}`;}if(cur)entries.push(cur);return entries.slice(0,80);}
function entry(name,description,section){const a=parseAttack(description);return{name:name.trim(),description:description.trim(),section,attack:/\b(?:melee|ranged)\s+(?:weapon\s+)?attack\b|\bto hit\b/i.test(description),...a};}
function parseAttack(text){const bonus=text.match(/([+-]\d+)\s*to\s*hit/i)?.[1],d=text.match(/(\d+)\s*d\s*(\d+)(?:\s*([+-])\s*(\d+))?\s*([a-z]+)?\s*damage/i),rr=text.match(/reach\s+(\d+)\s*ft/i),rg=text.match(/range\s+(\d+)\s*(?:\/\s*(\d+)\s*)?ft/i),ranged=/\branged\b/i.test(text);return{bonus:bonus==null?null:+bonus,number:d?+d[1]:1,die:d?`d${d[2]}`:"d6",modifier:d?.[4]?+(d[3]||"+")+d[4]:0,damageType:d?.[5]?.toLowerCase()||"",range:rg?+rg[1]:(rr?+rr[1]:(ranged?60:5)),longRange:rg?.[2]?+rg[2]:null,reach:rr?.[1]?+rr[1]:null,ranged};}
async function importMonster(text){const p=parseMonster(text),actor=await Actor.create({name:p.name,type:"npc"}),u={};if(p.ac!=null)u["system.attributes.ac.flat"]=p.ac;if(p.hp!=null){u["system.attributes.hp.value"]=p.hp;u["system.attributes.hp.max"]=p.hp;}if(p.formula)u["system.attributes.hp.formula"]=p.formula;if(p.speed!=null)u["system.attributes.movement.walk"]=p.speed;if(p.cr)u["system.details.cr"]=p.cr;if(p.prof!=null)u["system.attributes.prof"]=p.prof;if(p.passive!=null)u["system.attributes.senses.passive"]=p.passive;if(p.alignment)u["system.details.alignment"]=p.alignment;for(const[k,v]of Object.entries(p.abilities))u[`system.abilities.${k}.value`]=v;u["system.details.biography.value"]=sourceHtml(text);await actor.update(u);let weapons=0,attacks=0,lairs=0,actions=0;for(const e of p.entries){if(e.section.startsWith("lair")){await createLairAction(actor,e);lairs++;}else if(e.attack){await createAttackItem(actor,e);attacks++;}else{await createActionItem(actor,e);actions++;}}actor.sheet.render(true);ui.notifications.info(`Imported ${actor.name}: ${weapons} weapon(s), ${attacks} attack(s), ${actions} action(s), ${lairs} lair action(s).`);}
async function createActionItem(actor,e){return Item.create({name:e.name,type:"feat",system:{description:{value:`<p>${escapeHtml(e.description)}</p>`}}},{parent:actor});}
async function createLairAction(actor,e){return Item.create({name:`Lair Action: ${e.name}`,type:"feat",system:{description:{value:`<p><strong>Lair Action</strong></p><p>${escapeHtml(e.description)}</p>`}}},{parent:actor});}
async function createAttackItem(actor,e){const weapon=await Item.create({name:e.name,type:"weapon",system:{description:{value:`<p>${escapeHtml(e.description)}</p>`},actionType:e.ranged?"rwak":"mwak",ability:e.ranged?"dex":"str",attack:{bonus:e.bonus==null?"":String(e.bonus),flat:true},damage:{base:{number:e.number,denomination:e.die,bonus:e.modifier,types:e.damageType?[e.damageType]:[]}},range:{value:e.range,long:e.longRange,units:"ft"},equipped:true,proficient:true}},{parent:actor});return addActivity(weapon,e);}
async function addActivity(item,e){try{await item.update({"system.activities":{[foundry.utils.randomID()]:{type:"attack",name:"Attack",activation:{type:"action"},attack:{ability:e.ranged?"dex":"str",bonus:e.bonus==null?"":String(e.bonus),flat:true,type:{value:e.ranged?"ranged":"melee",classification:"weapon"}},damage:{includeBase:true}}}});}catch(err){console.warn(`${MODULE_ID} | Attack activity fallback used`,err);}}
function makeWeaponData(name,text){const e=parseAttack(text);return{name,type:"weapon",system:{description:{value:`<p>${escapeHtml(text)}</p>`},actionType:e.ranged?"rwak":"mwak",ability:e.ranged?"dex":"str",damage:{base:{number:e.number,denomination:e.die,bonus:e.modifier,types:e.damageType?[e.damageType]:[]}},range:{value:e.range,long:e.longRange,units:"ft"}};}
async function importStandaloneWeapon(text){const p=parseNamedEntry(text);const item=await Item.create(makeWeaponData(p.name,text));item.sheet.render(true);ui.notifications.info(`Created weapon: ${item.name}`);}
async function importStandaloneAttack(text){const p=parseNamedEntry(text),e={...parseAttack(text),name:p.name,description:text};const actor=await Actor.create({name:`${p.name} - Attack`,type:"npc"});await createAttackItem(actor,e);actor.sheet.render(true);ui.notifications.info(`Created attack: ${p.name}`);}
async function importLairAction(text){const p=parseNamedEntry(text);const actor=await Actor.create({name:`${p.name} - Lair`,type:"npc"});await createLairAction(actor,{name:p.name,description:text});actor.sheet.render(true);ui.notifications.info(`Created lair action: ${p.name}`);}
function parseNamedEntry(text){const lines=text.split("\n").map(clean).filter(Boolean);return{name:lines[0]||"Imported Entry"};}
async function importSimpleItem(text,type){const p=parseNamedEntry(text);const item=await Item.create({name:p.name,type,system:{description:{value:sourceHtml(text)}}});item.sheet.render(true);ui.notifications.info(`Created ${type}: ${item.name}`);}
function normalize(s){return String(s||"").replace(/\r/g,"\n").replace(/[\u00a0\u2007\u202f]/g," ").replace(/\n{3,}/g,"\n\n").trim();}
function clean(s){return String(s||"").replace(/\s+/g," ").trim();}
function flatten(s){return normalize(s).replace(/\n+/g," ").replace(/\s+/g," ");}
function escapeHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function sourceHtml(s){return `<p><strong>Imported by Statblock 5e</strong></p><pre>${escapeHtml(s)}</pre>`;}
