/* Statblock 5e v2.0.0 - Foundry VTT v14 / D&D5e v6 */
const MODULE_ID="statblock-5e"; const DND5E_TYPES=new Set(["race","class","subclass"]);
Hooks.once("init",()=>console.log(`${MODULE_ID} | Initializing`));
Hooks.once("ready",()=>{console.log(`${MODULE_ID} | Ready`);ui.notifications.info("Statblock 5e is ready. Use Import Statblock from the Actors directory.");});
Hooks.on("renderActorDirectory",(app,html)=>{const root=html instanceof HTMLElement?html:html?.[0];if(!root)return;const header=root.querySelector(".directory-header .action-buttons")||root.querySelector(".directory-header");if(!header||header.querySelector("[data-statblock-5e]"))return;const b=document.createElement("button");b.type="button";b.dataset.statblock5e="true";b.innerHTML='<i class="fa-solid fa-file-import"></i> Import Statblock';b.title="Import a D&D 5e statblock, species, class, or subclass";b.onclick=()=>openImporter();header.appendChild(b);});
function openImporter(){const D=foundry?.applications?.api?.DialogV2;if(!D){ui.notifications.error("Statblock 5e requires Foundry VTT v14 or newer.");return;}const content=`<div class="statblock-5e-importer"><p><strong>Paste text or choose a PDF/text file.</strong></p><div class="form-group"><label>Content type</label><select name="contentType"><option value="auto">Auto-detect</option><option value="monster">Monster / NPC</option><option value="race">Species / Race</option><option value="class">Class</option><option value="subclass">Subclass</option></select></div><div class="form-group"><label>PDF or text file</label><input id="sb5e-file" type="file" accept=".pdf,.txt,.md,.text,.json,application/pdf,text/plain,application/json"></div><div class="form-group"><label>Source text</label><textarea id="sb5e-text" name="sourceText" rows="18" placeholder="Paste a D&D 5e statblock here..."></textarea></div><p class="hint">PDF import supports text-based PDFs. Scanned/image-only PDFs require OCR first.</p></div>`;new D({window:{title:"Statblock 5e Importer",icon:"fa-solid fa-file-import"},position:{width:720},content,buttons:[{action:"import",label:"Import",icon:"fa-solid fa-file-import",default:true,callback:async(_e,button)=>{const form=button.form;const text=form.elements.sourceText.value.trim();if(!text){ui.notifications.warn("Paste text or choose a readable PDF/text file first.");return false;}await importContent(text,form.elements.contentType.value);return true;}},{action:"cancel",label:"Cancel",icon:"fa-solid fa-xmark"}],render:(_e,dialog)=>{dialog.element.querySelector("#sb5e-file")?.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{dialog.element.querySelector("#sb5e-text").value=await readSourceFile(f);ui.notifications.info(`Loaded ${f.name}. Review the text before importing.`);}catch(err){console.error(err);ui.notifications.error(err.message||"Could not read that file.");}});}}).render({force:true});}
async function readSourceFile(file){return file.name.toLowerCase().endsWith(".pdf")?extractPdfText(file):file.text();}
async function extractPdfText(file){const bytes=new Uint8Array(await file.arrayBuffer()),raw=new TextDecoder("latin1").decode(bytes),chunks=[];let cursor=0;while(cursor<raw.length){const s=raw.indexOf("stream",cursor);if(s<0)break;let a=s+6;if(raw[a]==="\r")a++;if(raw[a]==="\n")a++;const e=raw.indexOf("endstream",a);if(e<0)break;const h=raw.slice(Math.max(raw.lastIndexOf("obj",s-1),s-1200),s),sb=bytes.slice(a,e);let decoded=sb;try{if(/\/FlateDecode/.test(h)&&typeof DecompressionStream!=="undefined"){const ds=new DecompressionStream("deflate");decoded=new Uint8Array(await new Response(new Blob([sb]).stream().pipeThrough(ds)).arrayBuffer());}}catch(err){console.warn(`${MODULE_ID} | PDF decompression failed`,err);}const t=new TextDecoder("latin1").decode(decoded);if(t)chunks.push(extractPdfOperators(t));cursor=e+9;}const result=chunks.join("\n").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();if(!result)throw new Error("No selectable text was found in this PDF. If it is scanned, run OCR first.");return result;}
function extractPdfOperators(stream){const out=[],re=/\((?:\\.|[^\\)])*\)\s*Tj|\[(?:.|\n)*?\]\s*TJ/g;for(const m of stream.matchAll(re)){const s=m[0];const parts=s.match(/\((?:\\.|[^\\)])*\)/g)||[];out.push(parts.map(decodePdfString).join(""));}return out.join(" ");}
function decodePdfString(v){return v.slice(1,-1).replace(/\\([\\()])/g,"$1").replace(/\\n/g,"\n").replace(/\\r/g,"\n").replace(/\\t/g,"\t").replace(/\\([0-7]{1,3})/g,(_m,o)=>String.fromCharCode(parseInt(o,8)));}
async function importContent(text,type){type=type==="auto"?detectType(text):type;try{if(type==="monster")await createMonster(text);else if(DND5E_TYPES.has(type))await createDndItem(text,type);else throw new Error(`Unsupported content type: ${type}`);}catch(err){console.error(`${MODULE_ID} | Import failed`,err);ui.notifications.error(`Import failed: ${err.message}`);}}
function detectType(text){const t=normalize(text);if(/(?:armor class|ac)\s*\d+/i.test(t)&&/(?:hit points|hp)\s+\d+/i.test(t)&&/strength\s+\d+/i.test(t))return"monster";if(/subclass|subclass features|archetype|college|domain|circle|oath|patron|tradition|school/i.test(t))return"subclass";if(/hit die|class features|starting equipment|multiclassing/i.test(t))return"class";if(/ability score increase|species traits|racial traits|creature type/i.test(t))return"race";return"monster";}
async function createMonster(text){const p=parseMonster(text),actor=await Actor.create({name:p.name||"Imported Monster",type:"npc",system:{}}),u={};if(p.ac!=null)u["system.attributes.ac.flat"]=p.ac;if(p.hp!=null){u["system.attributes.hp.value"]=p.hp;u["system.attributes.hp.max"]=p.hp;}if(p.hpFormula)u["system.attributes.hp.formula"]=p.hpFormula;if(p.speed!=null)u["system.attributes.movement.walk"]=p.speed;for(const[a,v]of Object.entries(p.abilities))u[`system.abilities.${a}.value`]=v;if(p.cr)u["system.details.cr"]=p.cr;if(p.size)u["system.traits.size"]=p.size;u["system.details.biography.value"]=`<p><strong>Imported by Statblock 5e</strong></p><pre>${escapeHtml(text)}</pre>`;try{await actor.update(u);}catch(e){console.warn(`${MODULE_ID} | Some fields could not be applied`,e);}actor.sheet.render(true);ui.notifications.info(`Imported monster: ${actor.name}`);}
function parseMonster(text){const lines=normalize(text).split("\n").map(s=>s.trim()).filter(Boolean),flat=lines.join(" "),abilities={};for(const a of["str","dex","con","int","wis","cha"]){const m=flat.match(new RegExp(`\\b${a.toUpperCase()}\\s+(\\d+)\\b`,`i`));if(m)abilities[a]=+m[1];}const hm=flat.match(/(?:hit points|hp)\s+(\d+)(?:\s*\(([^)]+)\))?/i),sm=flat.match(/speed\s+(\d+)\s*ft\.?/i),cm=flat.match(/challenge\s+(\d+(?:\/\d+)?(?:\.\d+)?)/i);return{name:lines[0]||"Imported Monster",abilities,ac:numberAfter(flat,/(?:armor class|ac)\s+(\d+)/i),hp:hm?+hm[1]:null,hpFormula:hm?.[2]||"",speed:sm?+sm[1]:null,cr:cm?.[1],size:detectSize(flat)};}
function detectSize(t){return t.match(/\b(Tiny|Small|Medium|Large|Huge|Gargantuan)\b/i)?.[1]?.toLowerCase()?.[0]||null;}
function numberAfter(t,r){const m=t.match(r);return m?+m[1]:null;}
async function createDndItem(text,type){const p=parseItem(text),description=`<p><strong>Imported by Statblock 5e</strong></p><pre>${escapeHtml(text)}</pre>`,system={description:{value:description}};if(type==="class"){system.levels=p.levels||1;system.hitDie=p.hitDie||"d8";}if(type==="subclass"&&p.parentClass)system.classIdentifier=slugify(p.parentClass);const item=await Item.create({name:p.name||`Imported ${type}`,type,system});item.sheet.render(true);ui.notifications.info(`Imported ${type}: ${item.name}`);}
function parseItem(text){const l=normalize(text).split("\n").map(s=>s.trim()).filter(Boolean),f=l.join(" ");return{name:l[0]||"Imported Content",hitDie:f.match(/hit die\s*[:\-]?\s*(d\d+)/i)?.[1],levels:+(f.match(/(?:levels?|level)\s*[:\-]?\s*(\d+)/i)?.[1])||undefined,parentClass:f.match(/(?:class|parent class)\s*[:\-]?\s*([A-Za-z][A-Za-z ]{2,40})/i)?.[1]?.trim()};}
function normalize(t){return String(t).replace(/\r\n?/g,"\n").replace(/[\u00a0\u200b]/g," ").replace(/[ \t]+/g," ");}function slugify(v){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
